"""
Adalat-AI Document Registry
============================
Single source of truth for all 47 legal documents.
Every document ingested must have an entry here.

Fields:
    file_name       : exact filename in data/raw/
    title_en        : English title
    title_local     : local language title (Urdu/German if applicable)
    country         : PK / UK / DE
    jurisdiction    : federal / provincial / national
    province        : Punjab / Sindh / KP / Islamabad / None
    category        : tenancy / criminal / consumer / family /
                      labour / civil / constitutional / employment /
                      immigration
    language        : english / german / urdu
    enactment_year  : int
    source_url      : official source
    license         : public_domain / open_government / official
    priority        : 1=high 2=medium 3=low
    notes           : any special handling notes
"""

DOCUMENT_REGISTRY = [

    # ── ALREADY EMBEDDED (v1.0) ──────────────────────────────────

    {
        "file_name": "pakistan_constitution.pdf",
        "title_en": "Constitution of Pakistan 1973",
        "title_local": "آئین پاکستان",
        "country": "PK",
        "jurisdiction": "federal",
        "province": None,
        "category": "constitutional",
        "language": "english",
        "enactment_year": 1973,
        "source_url": "https://na.gov.pk",
        "license": "public_domain",
        "priority": 1,
        "notes": "Already embedded in v1.0",
        "embedded": True,
    },
    {
        "file_name": "pakistan_penal_code.pdf",
        "title_en": "Pakistan Penal Code 1860 (Act XLV of 1860)",
        "title_local": "تعزیرات پاکستان",
        "country": "PK",
        "jurisdiction": "federal",
        "province": None,
        "category": "criminal",
        "language": "english",
        "enactment_year": 1860,
        "source_url": "https://fmu.gov.pk",
        "license": "public_domain",
        "priority": 1,
        "notes": "Already embedded in v1.0",
        "embedded": True,
    },
    {
        "file_name": "uk_tenant_fees_act.pdf",
        "title_en": "Tenant Fees Act 2019",
        "title_local": None,
        "country": "UK",
        "jurisdiction": "national",
        "province": None,
        "category": "tenancy",
        "language": "english",
        "enactment_year": 2019,
        "source_url": "https://legislation.gov.uk",
        "license": "open_government",
        "priority": 1,
        "notes": "Already embedded in v1.0",
        "embedded": True,
    },
    {
        "file_name": "bgb_german_tenancy.pdf",
        "title_en": "German Civil Code BGB (Full English Translation 2021)",
        "title_local": "Bürgerliches Gesetzbuch",
        "country": "DE",
        "jurisdiction": "national",
        "province": None,
        "category": "tenancy",
        "language": "english",
        "enactment_year": 1900,
        "source_url": "https://gesetze-im-internet.de",
        "license": "public_domain",
        "priority": 1,
        "notes": "Already embedded in v1.0. §§535-548 subset only",
        "embedded": True,
    },

    # ── PAKISTAN — TENANCY ───────────────────────────────────────

    {
        "file_name": "pk-tenancy-punjab-rented-premises-act-2009.pdf",
        "title_en": "Punjab Rented Premises Act 2009",
        "title_local": "پنجاب کرایہ داری ایکٹ 2009",
        "country": "PK",
        "jurisdiction": "provincial",
        "province": "Punjab",
        "category": "tenancy",
        "language": "english",
        "enactment_year": 2009,
        "source_url": "https://punjablaws.gov.pk",
        "license": "public_domain",
        "priority": 1,
        "notes": "Phase 1 pilot document — medium complexity",
        "embedded": False,
    },
    {
        "file_name": "pk-tenancy-sindh-rented-premises-ordinance-1979-consolidated.pdf",
        "title_en": "Sindh Rented Premises Ordinance 1979 (Consolidated)",
        "title_local": "سندھ کرایہ داری آرڈیننس",
        "country": "PK",
        "jurisdiction": "provincial",
        "province": "Sindh",
        "category": "tenancy",
        "language": "english",
        "enactment_year": 1979,
        "source_url": "https://sindhlaws.gov.pk",
        "license": "public_domain",
        "priority": 1,
        "notes": "Use consolidated version over original",
        "embedded": False,
    },
    {
        "file_name": "pk-tenancy-sindh-rented-premises-ordinance-1979-original.pdf",
        "title_en": "Sindh Rented Premises Ordinance 1979 (Original)",
        "title_local": "سندھ کرایہ داری آرڈیننس",
        "country": "PK",
        "jurisdiction": "provincial",
        "province": "Sindh",
        "category": "tenancy",
        "language": "english",
        "enactment_year": 1979,
        "source_url": "https://sindhlaws.gov.pk",
        "license": "public_domain",
        "priority": 2,
        "notes": "Original version — use consolidated instead",
        "embedded": False,
    },
    {
        "file_name": "pk-tenancy-islamabad-rent-restriction-ordinance-2001.pdf",
        "title_en": "Islamabad Rent Restriction Ordinance 2001",
        "title_local": "اسلام آباد کرایہ پابندی آرڈیننس",
        "country": "PK",
        "jurisdiction": "federal",
        "province": "Islamabad",
        "category": "tenancy",
        "language": "english",
        "enactment_year": 2001,
        "source_url": "https://pakistancode.gov.pk",
        "license": "public_domain",
        "priority": 1,
        "notes": "Covers federal capital territory",
        "embedded": False,
    },
    {
        "file_name": "pk-tenancy-kp-restriction-rented-buildings-security-act-2014.pdf",
        "title_en": "KP Restriction and Rented Buildings Security Act 2014",
        "title_local": None,
        "country": "PK",
        "jurisdiction": "provincial",
        "province": "KPK",
        "category": "tenancy",
        "language": "english",
        "enactment_year": 2014,
        "source_url": "https://kpcode.gov.pk",
        "license": "public_domain",
        "priority": 1,
        "notes": None,
        "embedded": False,
    },
    {
        "file_name": "pk-tenancy-kp-west-pakistan-urban-rent-restriction-ordinance-1959.pdf",
        "title_en": "West Pakistan Urban Rent Restriction Ordinance 1959 (KP)",
        "title_local": None,
        "country": "PK",
        "jurisdiction": "provincial",
        "province": "KPK",
        "category": "tenancy",
        "language": "english",
        "enactment_year": 1959,
        "source_url": "https://kpcode.gov.pk",
        "license": "public_domain",
        "priority": 2,
        "notes": "Older ordinance, may be superseded",
        "embedded": False,
    },

    # ── PAKISTAN — CRIMINAL ──────────────────────────────────────

    {
        "file_name": "pk-criminal-code-criminal-procedure-crpc-1898.pdf",
        "title_en": "Code of Criminal Procedure 1898 (CrPC)",
        "title_local": "ضابطہ فوجداری",
        "country": "PK",
        "jurisdiction": "federal",
        "province": None,
        "category": "criminal",
        "language": "english",
        "enactment_year": 1898,
        "source_url": "https://pakistancode.gov.pk",
        "license": "public_domain",
        "priority": 1,
        "notes": "Phase 1 pilot — older/complex document",
        "embedded": False,
    },
    {
        "file_name": "pk-criminal-qanun-e-shahadat-evidence-order-1984.pdf",
        "title_en": "Qanun-e-Shahadat Order 1984 (Evidence Act)",
        "title_local": "قانون شہادت آرڈر",
        "country": "PK",
        "jurisdiction": "federal",
        "province": None,
        "category": "criminal",
        "language": "english",
        "enactment_year": 1984,
        "source_url": "https://pakistancode.gov.pk",
        "license": "public_domain",
        "priority": 1,
        "notes": None,
        "embedded": False,
    },
    {
        "file_name": "pk-criminal-anti-terrorism-act-1997.pdf",
        "title_en": "Anti-Terrorism Act 1997",
        "title_local": "انسداد دہشت گردی ایکٹ",
        "country": "PK",
        "jurisdiction": "federal",
        "province": None,
        "category": "criminal",
        "language": "english",
        "enactment_year": 1997,
        "source_url": "https://pakistancode.gov.pk",
        "license": "public_domain",
        "priority": 2,
        "notes": "Sensitive — add escalation cue in prompts",
        "embedded": False,
    },

    # ── PAKISTAN — CONSUMER ──────────────────────────────────────

    {
        "file_name": "pk-consumer-islamabad-consumers-protection-act-1995.pdf",
        "title_en": "Islamabad Consumer Protection Act 1995",
        "title_local": None,
        "country": "PK",
        "jurisdiction": "federal",
        "province": "Islamabad",
        "category": "consumer",
        "language": "english",
        "enactment_year": 1995,
        "source_url": "https://pakistancode.gov.pk",
        "license": "public_domain",
        "priority": 2,
        "notes": None,
        "embedded": False,
    },
    {
        "file_name": "pk-consumer-kp-consumer-protection-act-1997.pdf",
        "title_en": "KP Consumer Protection Act 1997",
        "title_local": None,
        "country": "PK",
        "jurisdiction": "provincial",
        "province": "KPK",
        "category": "consumer",
        "language": "english",
        "enactment_year": 1997,
        "source_url": "https://kpcode.gov.pk",
        "license": "public_domain",
        "priority": 2,
        "notes": None,
        "embedded": False,
    },
    {
        "file_name": "pk-consumer-punjab-consumer-protection-act-2005.pdf",
        "title_en": "Punjab Consumer Protection Act 2005",
        "title_local": None,
        "country": "PK",
        "jurisdiction": "provincial",
        "province": "Punjab",
        "category": "consumer",
        "language": "english",
        "enactment_year": 2005,
        "source_url": "https://punjablaws.gov.pk",
        "license": "public_domain",
        "priority": 1,
        "notes": None,
        "embedded": False,
    },
    {
        "file_name": "pk-consumer-punjab-consumer-protection-act-2005-fao-mirror.pdf",
        "title_en": "Punjab Consumer Protection Act 2005 (FAO Mirror)",
        "title_local": None,
        "country": "PK",
        "jurisdiction": "provincial",
        "province": "Punjab",
        "category": "consumer",
        "language": "english",
        "enactment_year": 2005,
        "source_url": "https://fao.org",
        "license": "public_domain",
        "priority": 3,
        "notes": "Duplicate of above — skip unless primary missing",
        "embedded": False,
    },

    # ── PAKISTAN — FAMILY ────────────────────────────────────────

    {
        "file_name": "pk-family-muslim-family-laws-ordinance-1961-federal.pdf",
        "title_en": "Muslim Family Laws Ordinance 1961 (Federal)",
        "title_local": "مسلم عائلی قوانین آرڈیننس",
        "country": "PK",
        "jurisdiction": "federal",
        "province": None,
        "category": "family",
        "language": "english",
        "enactment_year": 1961,
        "source_url": "https://pakistancode.gov.pk",
        "license": "public_domain",
        "priority": 1,
        "notes": "Covers marriage, divorce, inheritance",
        "embedded": False,
    },
    {
        "file_name": "pk-family-muslim-family-laws-ordinance-1961-punjab.pdf",
        "title_en": "Muslim Family Laws Ordinance 1961 (Punjab Version)",
        "title_local": "مسلم عائلی قوانین آرڈیننس پنجاب",
        "country": "PK",
        "jurisdiction": "provincial",
        "province": "Punjab",
        "category": "family",
        "language": "english",
        "enactment_year": 1961,
        "source_url": "https://punjablaws.gov.pk",
        "license": "public_domain",
        "priority": 2,
        "notes": "Punjab-specific amendments",
        "embedded": False,
    },
    {
        "file_name": "pk-family-family-courts-act-1964-federal.pdf",
        "title_en": "Family Courts Act 1964 (Federal)",
        "title_local": "عائلی عدالتوں کا ایکٹ",
        "country": "PK",
        "jurisdiction": "federal",
        "province": None,
        "category": "family",
        "language": "english",
        "enactment_year": 1964,
        "source_url": "https://pakistancode.gov.pk",
        "license": "public_domain",
        "priority": 1,
        "notes": None,
        "embedded": False,
    },
    {
        "file_name": "pk-family-family-courts-act-1964-kp.pdf",
        "title_en": "Family Courts Act 1964 (KP Version)",
        "title_local": None,
        "country": "PK",
        "jurisdiction": "provincial",
        "province": "KPK",
        "category": "family",
        "language": "english",
        "enactment_year": 1964,
        "source_url": "https://kpcode.gov.pk",
        "license": "public_domain",
        "priority": 2,
        "notes": "KP-specific amendments",
        "embedded": False,
    },

    # ── PAKISTAN — LABOUR ────────────────────────────────────────

    {
        "file_name": "pk-labour-industrial-relations-act-2012.pdf",
        "title_en": "Industrial Relations Act 2012",
        "title_local": None,
        "country": "PK",
        "jurisdiction": "federal",
        "province": None,
        "category": "labour",
        "language": "english",
        "enactment_year": 2012,
        "source_url": "https://pakistancode.gov.pk",
        "license": "public_domain",
        "priority": 1,
        "notes": None,
        "embedded": False,
    },
    {
        "file_name": "pk-labour-eobi-act-1976.pdf",
        "title_en": "Employees Old-Age Benefits Act 1976 (EOBI)",
        "title_local": None,
        "country": "PK",
        "jurisdiction": "federal",
        "province": None,
        "category": "labour",
        "language": "english",
        "enactment_year": 1976,
        "source_url": "https://pakistancode.gov.pk",
        "license": "public_domain",
        "priority": 1,
        "notes": None,
        "embedded": False,
    },
    {
        "file_name": "pk-labour-minimum-wages-ordinance-1961.pdf",
        "title_en": "Minimum Wages Ordinance 1961",
        "title_local": None,
        "country": "PK",
        "jurisdiction": "federal",
        "province": None,
        "category": "labour",
        "language": "english",
        "enactment_year": 1961,
        "source_url": "https://pakistancode.gov.pk",
        "license": "public_domain",
        "priority": 2,
        "notes": None,
        "embedded": False,
    },
    {
        "file_name": "pk-labour-punjab-minimum-wages-act-2019.pdf",
        "title_en": "Punjab Minimum Wages Act 2019",
        "title_local": None,
        "country": "PK",
        "jurisdiction": "provincial",
        "province": "Punjab",
        "category": "labour",
        "language": "english",
        "enactment_year": 2019,
        "source_url": "https://punjablaws.gov.pk",
        "license": "public_domain",
        "priority": 1,
        "notes": "More current than federal ordinance",
        "embedded": False,
    },

    # ── PAKISTAN — CIVIL ─────────────────────────────────────────

    {
        "file_name": "pk-civil-contract-act-1872.pdf",
        "title_en": "Contract Act 1872",
        "title_local": "معاہدہ ایکٹ",
        "country": "PK",
        "jurisdiction": "federal",
        "province": None,
        "category": "civil",
        "language": "english",
        "enactment_year": 1872,
        "source_url": "https://pakistancode.gov.pk",
        "license": "public_domain",
        "priority": 1,
        "notes": "Very old document — check for scanning issues",
        "embedded": False,
    },

    # ── UK — HOUSING / TENANCY ───────────────────────────────────

    {
        "file_name": "uk-housing-housing-act-1988.pdf",
        "title_en": "Housing Act 1988",
        "title_local": None,
        "country": "UK",
        "jurisdiction": "national",
        "province": None,
        "category": "tenancy",
        "language": "english",
        "enactment_year": 1988,
        "source_url": "https://legislation.gov.uk",
        "license": "open_government",
        "priority": 1,
        "notes": "Assured tenancy regime — very important",
        "embedded": False,
    },
    {
        "file_name": "uk-housing-housing-act-1996.pdf",
        "title_en": "Housing Act 1996",
        "title_local": None,
        "country": "UK",
        "jurisdiction": "national",
        "province": None,
        "category": "tenancy",
        "language": "english",
        "enactment_year": 1996,
        "source_url": "https://legislation.gov.uk",
        "license": "open_government",
        "priority": 1,
        "notes": None,
        "embedded": False,
    },
    {
        "file_name": "uk-housing-landlord-and-tenant-act-1985.pdf",
        "title_en": "Landlord and Tenant Act 1985",
        "title_local": None,
        "country": "UK",
        "jurisdiction": "national",
        "province": None,
        "category": "tenancy",
        "language": "english",
        "enactment_year": 1985,
        "source_url": "https://legislation.gov.uk",
        "license": "open_government",
        "priority": 1,
        "notes": "Repair obligations — very important",
        "embedded": False,
    },
    {
        "file_name": "uk-housing-homes-fitness-for-human-habitation-act-2018.pdf",
        "title_en": "Homes (Fitness for Human Habitation) Act 2018",
        "title_local": None,
        "country": "UK",
        "jurisdiction": "national",
        "province": None,
        "category": "tenancy",
        "language": "english",
        "enactment_year": 2018,
        "source_url": "https://legislation.gov.uk",
        "license": "open_government",
        "priority": 1,
        "notes": None,
        "embedded": False,
    },
    {
        "file_name": "uk-housing-homes-fitness-act-2018-explanatory-notes.pdf",
        "title_en": "Homes Fitness Act 2018 — Explanatory Notes",
        "title_local": None,
        "country": "UK",
        "jurisdiction": "national",
        "province": None,
        "category": "tenancy",
        "language": "english",
        "enactment_year": 2018,
        "source_url": "https://legislation.gov.uk",
        "license": "open_government",
        "priority": 2,
        "notes": "Explanatory notes — supplement to main Act",
        "embedded": False,
    },
    {
        "file_name": "uk-housing-renters-rights-act-2025.pdf",
        "title_en": "Renters Rights Act 2025",
        "title_local": None,
        "country": "UK",
        "jurisdiction": "national",
        "province": None,
        "category": "tenancy",
        "language": "english",
        "enactment_year": 2025,
        "source_url": "https://legislation.gov.uk",
        "license": "open_government",
        "priority": 1,
        "notes": "PARTIALLY IN FORCE — phased commencement. "
                 "Add currency_warning in prompts.",
        "embedded": False,
    },
    {
        "file_name": "uk-housing-renters-rights-act-2025-information-sheet.pdf",
        "title_en": "Renters Rights Act 2025 — Information Sheet",
        "title_local": None,
        "country": "UK",
        "jurisdiction": "national",
        "province": None,
        "category": "tenancy",
        "language": "english",
        "enactment_year": 2025,
        "source_url": "https://gov.uk",
        "license": "open_government",
        "priority": 2,
        "notes": "Plain English summary — good for RAG context",
        "embedded": False,
    },
    {
        "file_name": "uk-housing-renters-rights-act-2025-implementation-roadmap.pdf",
        "title_en": "Renters Rights Act 2025 — Implementation Roadmap",
        "title_local": None,
        "country": "UK",
        "jurisdiction": "national",
        "province": None,
        "category": "tenancy",
        "language": "english",
        "enactment_year": 2025,
        "source_url": "https://gov.uk",
        "license": "open_government",
        "priority": 2,
        "notes": "Phased commencement schedule — critical for "
                 "distinguishing in-force vs scheduled provisions",
        "embedded": False,
    },

    # ── UK — CONSUMER ────────────────────────────────────────────

    {
        "file_name": "uk-consumer-consumer-rights-act-2015.pdf",
        "title_en": "Consumer Rights Act 2015",
        "title_local": None,
        "country": "UK",
        "jurisdiction": "national",
        "province": None,
        "category": "consumer",
        "language": "english",
        "enactment_year": 2015,
        "source_url": "https://legislation.gov.uk",
        "license": "open_government",
        "priority": 1,
        "notes": None,
        "embedded": False,
    },
    {
        "file_name": "uk-consumer-protection-from-unfair-trading-regulations-2008.pdf",
        "title_en": "Consumer Protection from Unfair Trading Regulations 2008",
        "title_local": None,
        "country": "UK",
        "jurisdiction": "national",
        "province": None,
        "category": "consumer",
        "language": "english",
        "enactment_year": 2008,
        "source_url": "https://legislation.gov.uk",
        "license": "open_government",
        "priority": 1,
        "notes": None,
        "embedded": False,
    },

    # ── UK — EMPLOYMENT ──────────────────────────────────────────

    {
        "file_name": "uk-employment-employment-rights-act-1996.pdf",
        "title_en": "Employment Rights Act 1996",
        "title_local": None,
        "country": "UK",
        "jurisdiction": "national",
        "province": None,
        "category": "employment",
        "language": "english",
        "enactment_year": 1996,
        "source_url": "https://legislation.gov.uk",
        "license": "open_government",
        "priority": 1,
        "notes": None,
        "embedded": False,
    },
    {
        "file_name": "uk-employment-equality-act-2010.pdf",
        "title_en": "Equality Act 2010",
        "title_local": None,
        "country": "UK",
        "jurisdiction": "national",
        "province": None,
        "category": "employment",
        "language": "english",
        "enactment_year": 2010,
        "source_url": "https://legislation.gov.uk",
        "license": "open_government",
        "priority": 1,
        "notes": "Phase 1 pilot — clean born-digital PDF",
        "embedded": False,
    },

    # ── UK — IMMIGRATION ─────────────────────────────────────────

    {
        "file_name": "uk-immigration-british-nationality-act-1981.pdf",
        "title_en": "British Nationality Act 1981",
        "title_local": None,
        "country": "UK",
        "jurisdiction": "national",
        "province": None,
        "category": "immigration",
        "language": "english",
        "enactment_year": 1981,
        "source_url": "https://legislation.gov.uk",
        "license": "open_government",
        "priority": 1,
        "notes": None,
        "embedded": False,
    },
    {
        "file_name": "uk-immigration-immigration-act-1971.pdf",
        "title_en": "Immigration Act 1971",
        "title_local": None,
        "country": "UK",
        "jurisdiction": "national",
        "province": None,
        "category": "immigration",
        "language": "english",
        "enactment_year": 1971,
        "source_url": "https://legislation.gov.uk",
        "license": "open_government",
        "priority": 1,
        "notes": None,
        "embedded": False,
    },

    # ── GERMANY — CIVIL / TENANCY ────────────────────────────────

    {
        "file_name": "de-civil-bgb-english-translation-2021.pdf",
        "title_en": "German Civil Code BGB — Full English Translation 2021",
        "title_local": "Bürgerliches Gesetzbuch (BGB)",
        "country": "DE",
        "jurisdiction": "national",
        "province": None,
        "category": "civil",
        "language": "english",
        "enactment_year": 1900,
        "source_url": "https://gesetze-im-internet.de",
        "license": "public_domain",
        "priority": 1,
        "notes": "currency_warning: translation current to 10 Aug 2021",
        "embedded": False,
    },
    {
        "file_name": "de-civil-bgb-german-authoritative.pdf",
        "title_en": "German Civil Code BGB — Authoritative German Text",
        "title_local": "Bürgerliches Gesetzbuch (BGB) — Originaltext",
        "country": "DE",
        "jurisdiction": "national",
        "province": None,
        "category": "civil",
        "language": "german",
        "enactment_year": 1900,
        "source_url": "https://gesetze-im-internet.de",
        "license": "public_domain",
        "priority": 2,
        "notes": "Authoritative German text — use for German queries",
        "embedded": False,
    },
    {
        "file_name": "de-tenancy-mietrechtsreformgesetz-2001.pdf",
        "title_en": "Tenancy Law Reform Act 2001 (Mietrechtsreformgesetz)",
        "title_local": "Mietrechtsreformgesetz 2001",
        "country": "DE",
        "jurisdiction": "national",
        "province": None,
        "category": "tenancy",
        "language": "german",
        "enactment_year": 2001,
        "source_url": "https://gesetze-im-internet.de",
        "license": "public_domain",
        "priority": 2,
        "notes": "German only — add currency_warning",
        "embedded": False,
    },
    {
        "file_name": "de-tenancy-betriebskostenverordnung-german.pdf",
        "title_en": "Operating Costs Regulation (Betriebskostenverordnung)",
        "title_local": "Betriebskostenverordnung (BetrKV)",
        "country": "DE",
        "jurisdiction": "national",
        "province": None,
        "category": "tenancy",
        "language": "german",
        "enactment_year": 2003,
        "source_url": "https://gesetze-im-internet.de",
        "license": "public_domain",
        "priority": 1,
        "notes": "Utility cost rules for tenants — very relevant",
        "embedded": False,
    },

    # ── GERMANY — CONSUMER ───────────────────────────────────────

    {
        "file_name": "de-consumer-uwg-unfair-competition-english.pdf",
        "title_en": "Act Against Unfair Competition (UWG) — English",
        "title_local": "Gesetz gegen den unlauteren Wettbewerb (UWG)",
        "country": "DE",
        "jurisdiction": "national",
        "province": None,
        "category": "consumer",
        "language": "english",
        "enactment_year": 2004,
        "source_url": "https://gesetze-im-internet.de",
        "license": "public_domain",
        "priority": 2,
        "notes": None,
        "embedded": False,
    },
    {
        "file_name": "de-consumer-pangv-price-indication-regulation-german.pdf",
        "title_en": "Price Indication Regulation (PAngV)",
        "title_local": "Preisangabenverordnung (PAngV)",
        "country": "DE",
        "jurisdiction": "national",
        "province": None,
        "category": "consumer",
        "language": "german",
        "enactment_year": 1985,
        "source_url": "https://gesetze-im-internet.de",
        "license": "public_domain",
        "priority": 3,
        "notes": "German only — lower priority",
        "embedded": False,
    },
    {
        "file_name": "de-consumer-uklag-injunctions-act-german.pdf",
        "title_en": "Injunctions Act (UKlaG)",
        "title_local": "Unterlassungsklagengesetz (UKlaG)",
        "country": "DE",
        "jurisdiction": "national",
        "province": None,
        "category": "consumer",
        "language": "german",
        "enactment_year": 2001,
        "source_url": "https://gesetze-im-internet.de",
        "license": "public_domain",
        "priority": 3,
        "notes": "German only — lower priority",
        "embedded": False,
    },
]


# ── Helper functions ──────────────────────────────────────────────────────────

def get_by_filename(filename: str) -> dict:
    for doc in DOCUMENT_REGISTRY:
        if doc["file_name"] == filename:
            return doc
    return {}


def get_by_country(country: str) -> list:
    return [d for d in DOCUMENT_REGISTRY if d["country"] == country]


def get_by_category(category: str) -> list:
    return [d for d in DOCUMENT_REGISTRY if d["category"] == category]


def get_unembedded() -> list:
    return [d for d in DOCUMENT_REGISTRY if not d.get("embedded", False)]


def get_pilot_documents() -> list:
    return [d for d in DOCUMENT_REGISTRY if "Phase 1 pilot" in (d.get("notes") or "")]


def get_stats() -> dict:
    total = len(DOCUMENT_REGISTRY)
    embedded = sum(1 for d in DOCUMENT_REGISTRY if d.get("embedded"))
    by_country = {}
    by_category = {}
    for d in DOCUMENT_REGISTRY:
        by_country[d["country"]] = by_country.get(d["country"], 0) + 1
        by_category[d["category"]] = by_category.get(d["category"], 0) + 1
    return {
        "total": total,
        "embedded": embedded,
        "pending": total - embedded,
        "by_country": by_country,
        "by_category": by_category
    }


if __name__ == "__main__":
    stats = get_stats()
    print("\n=== ADALAT-AI DOCUMENT REGISTRY ===")
    print(f"Total documents : {stats['total']}")
    print(f"Already embedded: {stats['embedded']}")
    print(f"Pending ingestion: {stats['pending']}")
    print(f"\nBy country: {stats['by_country']}")
    print(f"By category: {stats['by_category']}")
    print(f"\nPhase 1 pilot documents:")
    for d in get_pilot_documents():
        print(f"  - {d['file_name']} [{d['country']}]")